use lettre::{
    message::header::ContentType,
    transport::smtp::authentication::Credentials,
    Message, SmtpTransport, Transport,
};
use std::env;

pub struct EmailService {
    smtp_host: String,
    smtp_port: u16,
    smtp_username: String,
    smtp_password: String,
    from_email: String,
    from_name: String,
}

impl EmailService {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self {
            smtp_host: env::var("SMTP_HOST").unwrap_or_else(|_| "smtp.gmail.com".to_string()),
            smtp_port: env::var("SMTP_PORT")
                .unwrap_or_else(|_| "587".to_string())
                .parse()
                .unwrap_or(587),
            smtp_username: env::var("SMTP_USERNAME")?,
            smtp_password: env::var("SMTP_PASSWORD")?,
            from_email: env::var("SMTP_FROM_EMAIL")
                .unwrap_or_else(|_| env::var("SMTP_USERNAME").unwrap_or_default()),
            from_name: env::var("SMTP_FROM_NAME")
                .unwrap_or_else(|_| "TerraTruce MCP".to_string()),
        })
    }

    /// Send a test email to verify SMTP configuration
    pub async fn send_test_email(&self, to_email: &str) -> Result<(), Box<dyn std::error::Error>> {
        let email = Message::builder()
            .from(format!("{} <{}>", self.from_name, self.from_email).parse()?)
            .to(to_email.parse()?)
            .subject("MCP Email Service Test")
            .header(ContentType::TEXT_HTML)
            .body(format!(
                r#"
                <html>
                <body style="font-family: Arial, sans-serif; padding: 20px;">
                    <h2 style="color: #4F46E5;">✅ MCP Email Service Test</h2>
                    <p>This is a test email from the TerraTruce MCP service.</p>
                    <p><strong>SMTP Configuration:</strong></p>
                    <ul>
                        <li>Host: {}</li>
                        <li>Port: {}</li>
                        <li>From: {} &lt;{}&gt;</li>
                    </ul>
                    <p style="color: #10B981; font-weight: bold;">✓ Email service is working correctly!</p>
                    <hr style="margin: 20px 0;">
                    <p style="color: #6B7280; font-size: 12px;">
                        Sent from TerraTruce Model Control Proxy<br>
                        Time: {}
                    </p>
                </body>
                </html>
                "#,
                self.smtp_host,
                self.smtp_port,
                self.from_name,
                self.from_email,
                chrono::Utc::now().to_rfc3339()
            ))?;

        let creds = Credentials::new(self.smtp_username.clone(), self.smtp_password.clone());

        let mailer = SmtpTransport::relay(&self.smtp_host)?
            .port(self.smtp_port)
            .credentials(creds)
            .build();

        mailer.send(&email)?;

        tracing::info!("✅ Test email sent successfully to {}", to_email);
        Ok(())
    }

    /// Send analysis report email
    pub async fn send_analysis_report(
        &self,
        to_email: &str,
        location: &str,
        analysis_summary: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let email = Message::builder()
            .from(format!("{} <{}>", self.from_name, self.from_email).parse()?)
            .to(to_email.parse()?)
            .subject(format!("Property Analysis Report: {}", location))
            .header(ContentType::TEXT_HTML)
            .body(format!(
                r#"
                <html>
                <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #F9FAFB;">
                    <div style="max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                        <h2 style="color: #4F46E5; margin-bottom: 20px;">📊 Property Analysis Report</h2>
                        <p style="font-size: 16px; color: #374151;"><strong>Location:</strong> {}</p>
                        <hr style="margin: 20px 0; border: none; border-top: 1px solid #E5E7EB;">
                        <div style="background: #F3F4F6; padding: 15px; border-radius: 8px; margin: 20px 0;">
                            <h3 style="color: #1F2937; margin-top: 0;">Analysis Summary</h3>
                            <pre style="white-space: pre-wrap; font-family: monospace; font-size: 12px; color: #4B5563;">{}</pre>
                        </div>
                        <p style="color: #6B7280; font-size: 14px; margin-top: 30px;">
                            This report was generated by TerraTruce MCP using AI-powered analysis.
                        </p>
                        <hr style="margin: 20px 0; border: none; border-top: 1px solid #E5E7EB;">
                        <p style="color: #9CA3AF; font-size: 12px;">
                            Generated: {}<br>
                            Powered by TerraTruce Model Control Proxy
                        </p>
                    </div>
                </body>
                </html>
                "#,
                location,
                analysis_summary,
                chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
            ))?;

        let creds = Credentials::new(self.smtp_username.clone(), self.smtp_password.clone());

        let mailer = SmtpTransport::relay(&self.smtp_host)?
            .port(self.smtp_port)
            .credentials(creds)
            .build();

        mailer.send(&email)?;

        tracing::info!("✅ Analysis report sent to {}", to_email);
        Ok(())
    }

    /// Check if email service is configured
    pub fn is_configured(&self) -> bool {
        !self.smtp_username.is_empty() && !self.smtp_password.is_empty()
    }
}
